### ISSUE TITLE
[Gameplay] Item Buildings increased Influenceradius

### ISSUE THREAD

**Issue by blastpv** [anno-mods/Spice-it-Up#15]
doubled the structure of the town hall, for this reason the radius does not work. solved by deleting one entry with GUID='100415'

**Comment by taubenangriff** [comment]
> doubled the structure of the town hall

Does this mean you copy+pasted it or something else?

This mod only works on the vanilla town hall.

**Comment by blastpv** [comment]
> > doubled the structure of the town hall
> 
> Does this mean you copy+pasted it or something else?
> 
> This mod only works on the vanilla town hall.

in the mod itself, the town hall is registered twice
