### ISSUE TITLE
No commuter pier in Enbesa

### ISSUE THREAD

**Issue by ernstbernst** [anno-mods/Spice-it-Up#17]
Hello,

I dont get the commuter pier in Enbesa. This mod is actívated in my Anno, Im using the Anno 1800 Mod Loader.
I get the commuter pier in New World and the Arctic. 

What should I do?

**Comment by PhillipAlpha** [comment]
got 1500 elders?

**Comment by ernstbernst** [comment]
Oh, yes, that was it! Sorry for making such a fuzz. But I think it should be noted somewhere that it is present but requires 1500 elders.

Maybe let it always be in the construction menu but greyed out/hang locked with a notice about the requirements is it is for other buildings.
________________________________
Från: PhillipAlpha ***@***.***>
Skickat: den 26 april 2022 15:18
Till: anno-mods/Spice-it-Up ***@***.***>
Kopia: Anders Gidlund ***@***.***>; Author ***@***.***>
Ämne: Re: [anno-mods/Spice-it-Up] No commuter pier in Enbesa (Issue #17)


got 1500 elders?
