### ISSUE TITLE
Harborlife Warehouse Depot is never actually unlocked

### ISSUE THREAD

**Issue by Shad0wlife** [anno-mods/Spice-it-Up#20]
The Depot/Warehouse combination in Harbourlife is never unlocked because the base Building (GUID 8855001) is never unlocked, only the upgrades.

If this is uninteded, a possible location to add it would be here in the 300 Workers Unlock together with the normal Harborlife Warehouse:

https://github.com/anno-mods/Spice-it-Up/blob/2016aa048c85287455bf74bdc34c64ec525b3f62/%5BAddon%5D%20Harborlife/data/config/export/main/asset/assets.xml#L10243-L10256

Both Depot-Warehouse and normal Warehouse say "UL 150W" at the top of the file, which probably should mean unlocked at 150 workers, but it was changed to 300 at some point, so I'd just guess that the Depot-Warehouse should also unlock there.

(If I should also check and possibly raise such documentation issues here, just put it in a reply to this issue :) )

Can be closed if the Depot-Warehouse not activating is intended.

**Comment by taubenangriff** [comment]
That's some old code stuff still in there, and I don't think it's intended to be unlocked.

**Comment by Shad0wlife** [comment]
Ok curious. I activated it in there by hand and it seems to work just fine. I like the flexibility in size it gives me. But I can also do that in the future as well, so you can decide what you need.

Maybe it was disabled because there is a separate mod on the nexus that has it as well I think?

**Comment by taubenangriff** [comment]
well, it's legacy code, and everything that should be in the mod is in there. thanks for keeping an eye out!

**Comment by Shad0wlife** [comment]
While trying to create my own mod to unlock that building separately I just realized that there IS an unlock trigger for the New World warehouse-depot building (GUID 8855005), right here:

https://github.com/anno-mods/Spice-it-Up/blob/ca947d99cab783acabd78eea2f5a3f7252377378/[Addon]%20Harborlife/data/config/export/main/asset/assets.xml#L10020
