### ISSUE TITLE
[No ingame issue!] Tier 4 Harborlife Warehouse is grouped under Warehouse Depots in the code

### ISSUE THREAD

**Issue by Shad0wlife** [anno-mods/Spice-it-Up#21]
Not an actual gameplay issue, but might make the code unneccessarily hard to maintain.

In the Harborlife assets.xml, the Tier 4 Warehouse ModOp/Asset is grouped as if it were a Tier 4 Warehouse Depot

https://github.com/anno-mods/Spice-it-Up/blob/2016aa048c85287455bf74bdc34c64ec525b3f62/%5BAddon%5D%20Harborlife/data/config/export/main/asset/assets.xml#L417-L468

In the Interest of readability, maybe move it into the warehouse section like so:
![grafik](https://user-images.githubusercontent.com/15235997/182428596-20d21cc7-f107-48a4-a528-e3b88bbf6cd3.png)

**Comment by taubenangriff** [comment]
Restructured the mod in 3.0.10
