### ISSUE TITLE
Electric Lighting instead of Wires not working

### ISSUE THREAD

**Issue by D3nnis3n** [anno-mods/Spice-it-Up#29]
Already been trying your updated package from the PR successfully, just in case you didn't notice, at least for me the "Electric Lighting instead of Wires" doesn't seem to work anymore.

**Comment by taubenangriff** [comment]
do you have the option to hide electricity poles activated?

**Comment by D3nnis3n** [comment]
I have them set to show, is that wrong? If i turn them off I also don't see any lights.

![image](https://user-images.githubusercontent.com/25908592/206931410-8b1cded4-d4dc-4d05-a34b-d778401ee2a0.png)
![image](https://user-images.githubusercontent.com/25908592/206931434-453cc817-8a36-4d6e-999c-12654523909d.png)
![image](https://user-images.githubusercontent.com/25908592/206931463-83a28f49-7ac8-48c8-a878-7eb021246501.png)

**Comment by D3nnis3n** [comment]
This has been proven to be on my end, antivirus somehow blocked loading some of the mods, while others worked. Super weird. Sorry for taking your time needlessly.
