### ISSUE TITLE
Post Office building in Harbor life

### ISSUE THREAD

**Issue by joshoftenly** [anno-mods/Spice-it-Up#33]
Hopefully I'm not just running an old version of Harbor life, I noticed there's all the new update buildings except the post office in Harbor life, particularly in the New World, this causes a major issue of not being able to fulfill the overseas mail when using the cities built on the harbor. Thanks guys!

**Comment by Shad0wlife** [comment]
Agreed, there's no post office or post box in Harborlife, that would be good to have, to not waste potential mail.
I have no idea how to make the harbor building models, otherwise I would try to do this myself, but alas, I can currently only support this issue.

**Comment by Shad0wlife** [comment]
I added it to the mod with PR #38 .
Will probably be included in the new update.
