### ISSUE TITLE
Add-on to More trade Contracts

### ISSUE THREAD

**Issue by Wolfman237** [anno-mods/Spice-it-Up#9]
Is it possible to extend the mod on the export side to export the different kinds of scap metal?

**Comment by taubenangriff** [comment]
The Trade Contract Mod adds Goods to the traders on the import side, the export side is a ProductFilter (GUID: 502222) and has nothing to do with the Import Traders.
You should be able to change the ProductFilter in the DocklandsScene (GUID: 132201) to one that does include scrap, but again, exports and Imports are coded in different manner, so the Trade Contract Mod will not get you far on this.
